spring.datasource.url=jdbc:postgresql://dpg-d877uti8qa3s73d28ui0-a.singapore-postgres.render.com/shopsphere_qplg?ssl=true
spring.datasource.username=shopsphere_qplg_user
spring.datasource.password=1ZL9iqAf8f0Z8JlnzARfOMTUQP1R2hnM
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
