spring.datasource.url=jdbc:postgresql://dpg-d877uti8qa3s73d28ui0-a.singapore-postgres.render.com/shopsphere_qplg?sslmode=require
spring.datasource.username=shopsphere_qplg_user
spring.datasource.password=1ZL9iqAf8f0Z8JlnzARfOMTUQP1R2hnM
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:10000}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# Email service placeholders bypass
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testuser@gmail.com
spring.mail.password=abcdedghijklnmop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT/Token placeholders bypass (Agar code me kahin use ho rha ho)
jwt.secret=mySuperSecretKeyForShopSphereBackend2026Project🚀
app.jwtSecret=mySuperSecretKeyForShopSphereBackend2026Project🚀
